springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    com.menkoagro.api: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
